---
title: "New Schedule"
author: "Andy Grogan-Kaylor"
date: "today"
format: 
  html:
    toc: true
    number-sections: false
    theme:
      light: cosmo
      dark: vapor
    echo: false
---

# New Schedule

```{r}
#| output: false

library(gt)

library(pander)

```

```{r}

week <- seq(1:13)

topic <- c("Introduction",
           "Review of Linear Model and Intro to Stata Graphing",
           "Contingency Tables",
           "Linear Probability Model and Logistic Regression",
           "LPM and Logistic 2",
           "Lab Day 1",
           "Interactions in Logistic Regression",
           "Ordered and Multinomial Logit",
           "Count Models",
           "Lab Day 2",
           "Multilevel Categorical Models for Longitudinal Data",
           "TBD",
           "Lab Day 3")

myschedule <- data.frame(week, topic)

pander(myschedule)

```

Possible topics for *TBD* include:

1. Causal Modeling
    + Fixed Effects Regression 
    + Propensity Scores
2. Visualizing Categorical Results 
3. Prediction (NEW)





