---
title: "How To Choose A Chart: An Intuitive Guide"
author: "Andy Grogan-Kaylor"
date: "`r Sys.Date()`"
output:
  bookdown::gitbook:
    split_by: none
    highlight: haddock
    config:
      toc:
        collapse: none
      download:
      - how-to-choose-a-chart-intuitive.pdf
      - how-to-choose-a-chart-intuitive.epub
  bookdown::epub_book: default  
  pdf_document: 
    fig_width: 10
    latex_engine: xelatex
  html_document:
    fig_width: 10
    highlight: haddock
    code_download: yes
mainfont: Futura
classoption: landscape
geometry: margin=.5in
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

library(ggplot2)

library(ggbeeswarm)

library(patchwork)

library(michigancolors)

```

A more *intuitive* guide to [*How To Choose A Chart*](https://agrogan1.github.io/dataviz/how-to-choose-a-chart/how-to-choose-a-chart-a-visual-guide.pdf).

```{r}

N <- 1000

predictor <- rbeta(N, 2, 7)

group <- factor(rbinom(N, 1, .4),
                levels = c(0, 1),
                labels = c("Group A", "Group B"))

outcome <- predictor + rnorm(N, 0, .5)

outcome <- ifelse(group == "Group B",
                  outcome + 1.5,
                  outcome)

outcomeC <- ifelse(outcome >= quantile(outcome, c(.50)),
                   1,
                   0)

outcomeC <- factor(outcomeC,
                   levels = c(0,1),
                   labels = c("Below Median", 
                              "At Or Above Median"))

t <- round(runif(N, 1, 7), 
           digits = 2)

outcome2 <- log(t) + rnorm(N, 0, 1)

mydata <- data.frame(predictor, 
                     group, 
                     outcome, 
                     outcomeC,
                     t,
                     outcome2)


```

```{r}

myoutcome <- ggplot(data = mydata,
                    aes(x = outcome,
                        fill = factor(1),
                        color = factor(2))) +
  labs(title = "How Many People Experience This Outcome?") +
  scale_color_manual(values = c(michigancolors("angell hall ash"), 
                                michigancolors("blue"))) +
  scale_fill_manual(values = c(michigancolors("blue"),
                               michigancolors("maize"))) +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        title = element_text(size = rel(.5)))

```

```{r}

mydensity <- myoutcome + geom_density() +
  labs(subtitle = "Density Plot")

myhistogram <- myoutcome + 
  geom_histogram() +
  labs(subtitle = "Histogram")

mybeeswarm <- myoutcome + 
  geom_beeswarm(aes(y = 1), 
                color = michigancolors("arboretum blue"),
                size = .25,
                groupOnX = FALSE) +
  labs(subtitle = "Beeswarm Plot",
       y = "") +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank())

mycomparison <- myoutcome + 
  geom_histogram(aes(fill = group, color = group)) + 
  facet_wrap(~group, ncol = 1) +
  labs(subtitle = "Histogram With Comparison")

mybar <- ggplot(data = mydata,
                aes(x = group,
                    fill = group)) +
  geom_bar() +
  scale_fill_manual(values = michigancolors()) +
  scale_color_manual(values = michigancolors("angell hall ash")) +
  labs(title = "How Many People Are In Each Group?",
       subtitle = "Bar Chart") +
  theme(legend.position = "none",
        title = element_text(size = rel(.5)))

mycomparisonC <- ggplot(data = mydata,
                        aes(x = outcomeC,
                            fill = group)) +
  geom_bar() + 
  facet_wrap(~group,
             ncol = 2) +
  scale_fill_manual(values = michigancolors()) +
  scale_color_manual(values = michigancolors("angell hall ash")) +
  labs(title = "How Many People Experience Each Outcome?",
       subtitle = "Bar Chart With Comparison",
       x = "") +
  theme(legend.position = "none",
        title = element_text(size = rel(.5)),
        axis.text.x = element_text(size = rel(.5)))

mypie <- ggplot(data = mydata,
                aes(x = 1,
                    fill = group)) +
  geom_bar() +
  coord_polar(theta = "y") +
  scale_fill_manual(values = michigancolors()) +
  labs(title = "How Many People Are In Each Group?",
       subtitle = "Pie Chart") +
  theme_void() +
  theme(title = element_text(size = rel(.5)),
        legend.position = "none")
  
myscatterplot <- ggplot(mydata,
                        aes(x = predictor,
                            y = outcome,
                            color = factor(1))) +
  geom_point() +
  geom_smooth(color = michigancolors("arboretum blue")) +
  scale_color_manual(values = michigancolors("matthaei violet")) +
  labs(title = "What is the Relationship of Predictor to Outcome?",
       subtitle = "Scatterplot") +
  theme(legend.position = "none",
        title = element_text(size = rel(.5)))
  
mylongitudinal <- ggplot(mydata,
                         aes(x = t,
                             y = outcome2,
                             color = factor(1))) +
  geom_point() +
  geom_smooth(color = michigancolors("arboretum blue")) +
  scale_color_manual(values = michigancolors("wave field green")) +
  labs(title = "Is the Outcome Changing Over Time?",
       subtitle = "Scatterplot",
       x = "time",
       y = "outcome") +
  theme(legend.position = "none",
        title = element_text(size = rel(.5)),
        axis.text.y = element_blank(),
        axis.ticks.y=element_blank())

```

```{r}

# layout <- c(
#   area(1, 1, 1, 1),
#   area(1, 2, 1, 2),
#   area(1, 3, 1, 3), 
#   area(3, 1, 3, 2)
# )
# 
# plot(layout)
# 
# p1 <- myhistogram + 
#   mycomparison + 
#   mybeeswarm + 
#   myscatterplot +
#   plot_layout(design = layout)
# 
# p1

p0 <- myhistogram + mycomparison + mybeeswarm +
  mybar + mycomparisonC + mylongitudinal +
  plot_layout(ncol = 3, nrow = 2, widths = 1)

p0 # replay

p0A <- p0 + 
  plot_annotation(title = 'How To Choose A Chart', 
                  subtitle = 'An Intuitive Guide')

ggsave("intuitive-guide.pdf", 
       p0A,
       width = 10, 
       height = 7.5)

```

