---
title: "GLM Gallery"
description: |
  A Gallery of Generalized Linear Models 
author:
  - name: Andy Grogan-Kaylor 
    url: https://agrogan1.github.io/newstuff
    affiliation: University of Michigan
    affiliation_url: https://www.umich.edu
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```

```{r}

library(ggplot2)

library(dplyr)

library(plotly)

library(knitr)

library(rgl)

library(rayshader)

```

```{r}

load("../glm.RData")

```

All of these images are *manipulable*.

# Logit

```{r logit, fig.cap="Logistic Curve"}

knit_hooks$set(webgl = hook_webgl)

rayshader::plot_gg(p1, zoom = .8) 

rglwidget()
 
```

# Probit

```{r probit, fig.cap="Probit Curve"}

rgl.clear()

knit_hooks$set(webgl = hook_webgl)

rayshader::plot_gg(p2, zoom = .8) 

rglwidget()
 
```

# Negative Binomial

```{r negbin1, fig.cap="Negative Binomial Distribution"}

rgl.clear()

knit_hooks$set(webgl = hook_webgl)

rayshader::plot_gg(p3, zoom = .8) 

rglwidget()
 
```

```{r negbin2, fig.cap="Negative Binomial Curve"}

rgl.clear()

knit_hooks$set(webgl = hook_webgl)

rayshader::plot_gg(p4, zoom = .8) 

rglwidget()
 
```












