---
title: "Describing Odds Ratios"
subtitle: "Comments Welcome"
author: "Andy Grogan-Kaylor"
date: "today"
format:
  html:
    toc: false
    number-sections: false
    theme: yeti
    css: styles.css
    lightbox: true
  pdf:
    toc: false
    number-sections: false
    header-includes:
      - \usepackage{colortbl}\rowcolors{2}{lightgray!50}{white}
---

# Describing Odds Ratios

-------------------------------------------------------------
Odds Ratio for Group A   Interpretations
Compared to Another
Group
------------------------ ------------------------------------
.25                       The odds of the outcome for Group A
                          were 25% of the odds of the other 
                          group.
                          
                          The odds of the outcome for Group A
                          were 75% lower than for the other 
                          group.

1.0                       The odds of the outcome for Group A
                          were equivalent to (the same as)
                          the odds for the other group.
                          
                          There was no difference between Group A
                          and the other group.
                          
1.5                       The odds of the outcome for Group A
                          were 1.5 times those for the other 
                          group.
                          
                          The odds of the outcome for Group A
                          were 50% higher than for the other 
                          group.
                          
2.0                       The odds of the outcome for Group A 
                          were 100% higher than those for the
                          other group. (technically correct,
                          but at the very least confusing?)
                          
                          The odds of the outcome for Group A
                          were 2.0 (twice) those for the other
                          group.
                          
2.5                       The odds of the outcome for Group A
                          were 2.5 times those for the other 
                          group.
                          
                          The odds of the outcome for Group A
                          were 150% higher than for the other
                          group. (technically correct,
                          but at the very least confusing?)
                          
-------------------------------------------------------------

