---
title: "Descriptive Statistics"
output:
  revealjs::revealjs_presentation:
    fig_height: 4
    reveal_options:
      chalkboard:
        theme: chalkboard
        toggleNotesButton: yes
    reveal_plugins:
    - chalkboard
    - zoom
    self_contained: no
  html_document:
    code_download: yes
    fig_height: 3
    highlight: haddock
    number_sections: yes
    theme: default
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  pdf_document: 
    fig_height: 3
    latex_engine: xelatex
    number_sections: yes
    toc: yes
mainfont: Arial
fontsize: 11pt
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)

```

```{css, echo=FALSE}

h1, h2 {
  color: navy;
  font-family: "Helvetica", "Arial", sans-serif; 
  font-weight: normal;
}
.list-group-item.active, 
.list-group-item.active:focus, 
.list-group-item.active:hover {
    z-index: 2;
    color: gold;
    background-color: navy;
    border-color: blue;
}
.nav-pills > li.active > a, .nav-pills > li.active > a:focus {
    color: gold;
    background-color: navy;
}
.nav-pills > li.active > a:hover {
    color: gold;
    background-color: navy;

}
.caption { 
  display: block;
  color: #00274C;
  font-weight: bold;
}

```

# Get The Data

## Simulated Social Service Agency Data

```{r}

library(readxl)

clients <- read_excel("../../social-service-agency/social-service-agency.xlsx", sheet = "clients")

head(clients) # look at the data

```

# Continuous Variable

## Descriptive Statistics

```{r}

summary(clients$age)

```

## Graph of Continuous Variable (1)

```{r}

hist(clients$age)

```

## Graph of Continuous Variable (2)

```{r}

boxplot(clients$age)

```

## Graph of Continuous Variable (3, ggplot)

```{r}

library(ggplot2)

ggplot(clients,
       aes(x = age)) +
  geom_histogram(fill = "blue", color = "grey")

```

# Categorical Variable

## Descriptive Statistics

```{r}

table(clients$program)

```

## Graph of Categorical Variable

```{r}

barplot(table(clients$program))

```

## Graph of Categorical Variable (2)

```{r}

pie(table(clients$program))

```

## Graph of Categorical Variable (3, ggplot)

```{r}

ggplot(clients,
       aes(x = program,
           fill = program)) +
  geom_bar()

```

