---
title: "Index of Blog-ish Posts"
author:
  - name: Andy Grogan-Kaylor 
    url: https://agrogan1.github.io/
    affiliation: University of Michigan
    affiliation_url: https://umich.edu/
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    highlight: haddock
    toc: yes
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

library(icon)

```

# Posts

```{r}

library(dplyr) # data wrangling

library(DT) # nice data table

library(tibble) # tibbles

# get info about my HTML files

myHTMLfiles = file.info(list.files(pattern="*html"))

save(myHTMLfiles, file = "myHTMLfiles.RData")

# make a nicely formatted, labeled and sorted datatable
# of my files

myHTMLfiles %>% 
  rownames_to_column(var = "filename") %>% # rownames to column
  mutate(modified = mtime) %>% # copy mtime to modified
  mutate(url = paste0("<a href='", # paste together URL
                      filename,
                      "'>",
                      filename, 
                      "</a>")) %>% 
  select(modified, url) %>% # select columns
  arrange(desc(modified)) %>%
  datatable(rownames = FALSE, # no row names
            escape = 1, # escape URL column
            caption = "Blog-ish Posts",
            # sort by descending date
            # options = list(order = list(list(1, 'desc')))
  ) %>% 
  formatDate(1, 'toDateString') # format column 1 as dates
  
  
```

# Credits

[https://www.umich.edu/~agrogan/](https://www.umich.edu/~agrogan/)



