---
title: "Table Demo"
author: "Andy Grogan-Kaylor"
date: "`r Sys.Date()`"
output:
  html_document: 
    highlight: haddock
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    number_sections: yes
    fig_height: 3
  pdf_document: 
    toc: yes
    fig_height: 3
    number_sections: yes
    highlight: default
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

* [See the RMarkdown that generated this file](https://github.com/agrogan1/newstuff/blob/master/myposts/table-demo.Rmd)
* [PDF looks great too!](./table-demo.pdf)

# Get Data

```{r}

data("mtcars")

```

# Replay The Data Set (May Not Look So Great)

```{r}

mtcars

```

# Descriptive Statistics

```{r}

# summary(mtcars)

psych::describe(mtcars)

```

# Use Pander To Format Our Summary Results

```{r}

library(pander)

pander(psych::describe(mtcars))

```

# Only Look At A Subset of Variables

```{r}

mynewdata <- subset(mtcars, select = c(mpg, hp))

pander(psych::describe(mynewdata))

```
# "Hand Built" Table

-------------------------------------
Things   Outcome
------   -------
Thing 1   A

Thing 2   B
-------------------------------------
